apps:
  argocd:
    enabled: true
    namespace: argocd
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.0.14
    server:
      service:
        type: NodePort
        nodePortHttp: 30080
