version: "3"

tasks:
  add_NFS_mount:
    desc: Add a mount to the csi-driver-nfs (adds the nfs-client storage class)
    cmds:
      - helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
      - |
        helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
        --set nfs.server=192.168.50.122 \
        --set nfs.path=/volume1/k8sNFS
