apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{.Values.apps.argocd.repoURL}}
    chart: {{.Values.apps.argocd.chart}}
    targetRevision: {{.Values.apps.argocd.targetRevision}}
    helm:
      values: |
        server:
          service:
            type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: {{.Values.apps.argocd.namespace}}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-cd
  namespace: argocd
spec:
  parentRefs:
    - name: gateway
      namespace: gateway-system
  hostnames:
    - "argocd.local"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
