apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{.Values.apps.argocd.repoURL}}
    chart: {{.Values.apps.argocd.chart}}
    targetRevision: {{.Values.apps.argocd.targetRevision}}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{.Values.apps.argocd.namespace}}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
