apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{.Values.apps.argo-cd.repoURL}}
    chart: {{.Values.apps.argo-cd.chart}}
    targetRevision: {{.Values.apps.argo-cd.targetRevision}}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{.Values.apps.argo-cd.namespace}}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
