apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflare-tunnel
    targetRevision: 0.3.2
    helm:
      values: |
        cloudflare:
          tunnelName: "homelab"
          secretName: "cloudflared-credentials"
          ingress:
            - hostname: "nextjs.klaassen.dev"
              service: http://nextjs-example-nextjs-app.nextjs-example.svc:80
              originRequest:
                connectTimeout: "30s"
                retries: 5
            - hostname: "nginx.klaassen.dev"
              service: http://hello-world-nginx.hello-world.svc:80
              originRequest:
                connectTimeout: "30s"
                retries: 5
        logLevel: "info"
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/homelab/items/cloudflared-credentials"
  secretName: cloudflared-credentials
