apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://blakeblackshear.github.io/blakeshome-charts/
    chart: frigate
    targetRevision: 7.3.0
    helm:
      values: |
        mqtt:
          enabled: false
        cameras:
          esp32cam:
            ffmpeg:
              inputs:
                - path: rtsp://esp32.local:554/mjpeg/1
                  roles: [detect]
            detect:
              width: 640
              height: 480
              fps: 1
        persistence:
          config:
            enabled: false
        service:
          type: NodePort
          nodePorts:
            http: 30420
  destination:
    server: https://kubernetes.default.svc
    namespace: frigate
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
