apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: klaassen-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 21.0.0
    helm:
      values: |
        wordpressUsername: admin
        wordpressPassword: password
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
