apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: klaassen-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 21.0.0
    helm:
      values: |
        replicaCount: 1
        wordpressUsername: admin
        wordpressPassword: password
        containerSecurityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
        podSecurityContext:
          runAsUser: 0
        volumePermissions:
          enabled: true
        service:
          type: NodePort
          nodePorts:
            http: 30083
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
