apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 75.15.1
    helm:
      skipCRDs: true
      values: |
        prometheus:
          prometheusSpec:
            retention: 30d
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 512Mi
                cpu: 500m
    ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        name: alertmanagerconfigs.monitoring.coreos.com
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        name: alertmanagers.monitoring.coreos.com
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        name: prometheusagents.monitoring.coreos.com
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        name: prometheuses.monitoring.coreos.com
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        name: scrapeconfigs.monitoring.coreos.com
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        name: thanosrulers.monitoring.coreos.com
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  syncOptions:
    - ServerSideApply=true
