apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 75.15.1
    helm:
      values: |
        crds:
          enabled: true
          ## The CRD upgrade job mitigates the limitation of helm not being able to upgrade CRDs.
          ## The job will apply the CRDs to the cluster before the operator is deployed, using helm hooks.
          ## It deploy a corresponding clusterrole, clusterrolebinding and serviceaccount to apply the CRDs.
          ## This feature is in preview, off by default and may change in the future.
          upgradeJob:
            enabled: true
            forceConflicts: true
        prometheus:
          prometheusSpec:
            retention: 30d
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 512Mi
                cpu: 500m
        prometheusOperator:
          enabled: true
          createCustomResource: true
          admissionWebhooks:
            enabled: true

            annotations:
              argocd.argoproj.io/hook: PreSync
              argocd.argoproj.io/hook-delete-policy: HookFailed

            patch:
              annotations:
                argocd.argoproj.io/hook: PreSync
                argocd.argoproj.io/hook-delete-policy: HookFailed

            mutatingWebhookConfiguration:
              annotations:
                argocd.argoproj.io/hook: PreSync

            validatingWebhookConfiguration:
              annotations:
                argocd.argoproj.io/hook: PreSync

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
